### ISSUE TITLE
[4.x] Cannot open PROFILES_PATH directory if it does not exist

### ISSUE THREAD

**Issue by Spartan322** [Orama-Interactive/Keychain#7]
Its a result of not creating the directory as DirAccess does not create directories with open.

https://github.com/Orama-Interactive/Keychain/commit/cb41b92c55d35b4803ffadaf2b8d66e18a0ba428#r101041267:
> This will fail if the directory does not exist, should do `DirAccess.make_dir_absolute_recursive(PROFILES_PATH)` to create the directory first.

**Comment by OverloadedOrama** [comment]
Should be fixed in a197526f8b414ba36b19bab8234c3909c77a1f53.
