### ISSUE TITLE
[4.x] `ShortcutEdit.event_to_str` will produce an incomplete event string if modifiers are pressed

### ISSUE THREAD

**Issue by Spartan322** [Orama-Interactive/Keychain#8]
https://github.com/Orama-Interactive/Keychain/blob/cb41b92c55d35b4803ffadaf2b8d66e18a0ba428/addons/keychain/ShortcutEdit.gd#L256-L262

`Event.get_keycode_with_modifiers` will never be 0 if a modifier is pressed, so in the case you use physical keycodes in the InputMap, it will never refer to the physical keycode and so if you have `Ctrl+A` for your action, it will instead report `Ctrl+` skipping over the physical keycode retrieval. Should check if `event.keycode == 0`.

**Comment by OverloadedOrama** [comment]
Should be fixed by c1089fbc3b0c42190b7d56e39a1926e30de54705.
